### ISSUE TITLE
git p4 sync ?

### ISSUE THREAD

**Issue by MathieuNls** [salesforce/p4-fusion#2]
Hi,

Thanks for open sourcing this tool. It's definitely very fast when compared to git-p4.py

Do you plan to add the [`sync`](https://git-scm.com/docs/git-p4#_sync) command ?

I am willing contribute its implementation if you can give me some pointers on how you'd like it done.

Thanks,
Mathieu.

**Comment by MathieuNls** [comment]
Ok ... I found out that p4-fusion clones or sync automatically if it detects a HEAD that exists. However, it only detects heads when `--src` contains a `.git` as mentioned in the [doc](https://github.com/salesforce/p4-fusion/blob/master/README.md?plain=1#L104). If `--src clones` is used instead of `--src-clones/.git" then repository is re-cloned instead of being updated.

**Comment by twarit-waikar** [comment]
Thanks for looking into this. Yes, if the clone paths are different, p4-fusion will not sync the new changes. To sync the changes, the clone path needs to be the same as before.

**Comment by twarit-waikar** [comment]
I will change the occurrences of `clones/` to `clones/.git` in the README to make this clearer
