### ISSUE TITLE
How to insert P4PASSWD in order to use p4-fusion?

### ISSUE THREAD

**Issue by bonohubby** [salesforce/p4-fusion#76]
Hello, I have been trying to use p4-fusion.

But, I don't know where I should insert a P4PASSWD value.

I tried setting it to the environment but it did not work.

I would appreciate it if you could let me know.

**Comment by twarit-waikar** [comment]
Try running `p4 -u <username> -p <port> login` before you run this tool. Make sure to use the same user and port values when you invoke p4-fusion.

**Comment by bonohubby** [comment]
I will try it! Thank you for your kind answer
